name: twind_generator
description: Code generator for twind package.
version: 0.0.4
repository: 'https://github.com/shreyassanthu77/twind'
resolution: workspace
environment:
  sdk: ^3.10.1
dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  source_gen: ^4.1.1
  twind: ^0.0.3
dev_dependencies:
  test: ^1.24.0
